# Generated by Django 5.1.4 on 2025-05-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
